kafka:
  bootstrap-servers: localhost:9092
  topic:
    helloworld: helloworld1
    inputstream: streams-wordcount-input
    outputstream: streams-wordcount-output
    
#spring:
#  kafka:
#    bootstrap-servers: 
#    - localhost:9092
#    
#    clientId: 
