version: '2'
services:
  zookeeper:
    image: "confluentinc/cp-zookeeper"
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  kafka:
    image: "confluentinc/cp-kafka"
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092

  schema-registry:
    image: "confluentinc/cp-schema-registry"
    container_name: schema-registry
    ports:
      - "8081:8081"
    depends_on:
      - zookeeper
      - kafka
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8081

  kafka-rest:
    image: "confluentinc/cp-kafka-rest"
    container_name: kafka-rest
    ports:
      - "8082:8082"
    environment:
     - ACCESS_CONTROL_ALLOW_ORIGIN_DEFAULT="*"
     - KAFKA_REST_SCHEMA_REGISTRY_URL=http://schema-registry:8081
     - KAFKA_REST_ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_REST_LISTENERS=http://kafka-rest:8082
     - KAFKA_REST_HOST_NAME=kafka-rest
    depends_on:
      - kafka
      - schema-registry
      - zookeeper

  kafka-topic-ui:
    image: "landoop/kafka-topics-ui"
    container_name: kafka-topics-ui
    ports:
      - "8000:8000"
    environment:
      - KAFKA_REST_PROXY_URL=http://kafka-rest:8082
      - SCHEMAREGISTRY_UI_URL=http://schema-registry:8081
      - KAFKA_REST_BOOTSTRAP_SERVERS=PLAINTEXT://kafka:9092
      - PROXY=true
    depends_on:
      - kafka
      - schema-registry
      - zookeeper
      - kafka-rest